---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.xml: |
    <Config>
      <AuthenticationMethod>{{ .Values.prowlarr.authenticationMethod }}</AuthenticationMethod>
    </Config>
