---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

controllers:
  main:
    # @ignore
    type: deployment
    # -- Number of desired pods. When using a HorizontalPodAutoscaler, set this to `null`
    # @section -- Controller configuration
    replicas: 1
    # @ignore
    pod:
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsUser: 65534
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    containers:
      main:
        image:
          # -- Image repository
          # @section -- Controller configuration
          repository: ghcr.io/home-operations/prowlarr
          # -- Image tag
          # @section -- Controller configuration
          tag: 1.35.1
        env:
          # -- Prowlarr authentication method. `Basic`, `Forms`, or `External`
          # @section -- Controller configuration
          PROWLARR__AUTH__METHOD: ~
        # @ignore
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"

persistence:
  config:
    # -- Enable Prowlarr persistence
    # @section -- Persistence configuration
    enabled: false
    # @ignore
    name: prowlarr-config
    # -- Storage class for the config volume
    # @section -- Persistence configuration
    storageClass: ~
    # @ignore
    accessMode: ReadWriteOnce
    # -- Size of the config volume
    # @section -- Persistence configuration
    size: 8Gi
    # -- Whether or not the config volume is deleted on helm uninstall
    # @section -- Persistence configuration
    retain: true
    # @ignore
    globalMounts:
      - path: /config

# @ignore
service:
  main:
    controller: main
    ports:
      http:
        port: 9696
        protocol: HTTP
